// Generated by Wrangler by running `wrangler types`

interface Env {
	SOLANA_CLUSTER: "devnet";
	SOLANA_ENDPOINT: "https://api.devnet.solana.com";
	SOLANA_ENDPOINT_PUBLIC: "https://api.devnet.solana.com";
}
